const SITEMAP_CACHE_STALE_SECONDS = 300
const SITEMAP_CACHE_REVALIDATE_SECONDS = 3600
const SITEMAP_CACHE_EXPIRE_SECONDS = 86_400

export const SITEMAP_ENTITY_LIMIT = 2000

export const SITEMAP_CACHE_LIFE = {
    stale: SITEMAP_CACHE_STALE_SECONDS,
    revalidate: SITEMAP_CACHE_REVALIDATE_SECONDS,
    expire: SITEMAP_CACHE_EXPIRE_SECONDS,
}
